url: 
baseurl:

# Site settings
title: DDSCC
email: info@ddscc.nl
description: "Dutch Data Security & Compliance Community"


# Team names, titles and social links
people:
- name: Bram de Jager
  pic: 1
  pic_url: "/img/bram.jpeg"
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/bramdejager/

- name: René Laas
  pic: 2
  pic_url: "/img/rene.jpeg"
  position: Organisator
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/renelaas/

- name: Jeroen Bijdevier
  pic: 3
  pic_url: "/img/jeroen.jpeg"
  position: Organisator
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jeroenbijdevier/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: meetup
    url: https://www.meetup.com/nl-NL/dutch-data-security-compliance-community/
  - title: linkedin
    url: https://www.linkedin.com/company/ddscc/

# Postal address (add as many lines as necessary)
address:
  - line: 


# Build settings
markdown: kramdown
permalink: pretty