url: 
baseurl:

# Site settings
title: DDSCC
email: info@ddscc.nl
description: "Dutch Data Security and Compliance Community"


# Team names, titles and social links
people:
- name: Bram de Jager
  pic: 1
  pic_url: https://media.licdn.com/dms/image/C4E03AQEpHTurhuIkUw/profile-displayphoto-shrink_800_800/0/1526538536475?e=1727913600&v=beta&t=ChWvrc82vbMocfr6kRLW4tOFs6ewE5oH-GkKGIouokI
  position: Organisator
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #
    - title: github
      url: #

- name: Freerk Terpstra
  pic: 2
  pic_url: https://media.licdn.com/dms/image/D4E03AQGsBOOY_8rrTw/profile-displayphoto-shrink_800_800/0/1677647259774?e=1727913600&v=beta&t=TGIRF6i876JSX9VMlJEOckg3WWyxSCnWYwRm9VnE6Rs
  position: Organisator
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #
    - title: github
      url: #

- name: René Laas
  pic: 3
  pic_url: https://media.licdn.com/dms/image/C4D03AQHXhHCjoByNsg/profile-displayphoto-shrink_800_800/0/1625832708217?e=1727913600&v=beta&t=0KNTvud8YegiiMWvPiKKjoboW-wHwU2cqdjeRS5IcT4
  position: Organisator
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #
    - title: github
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: meetup
    url: http://twitter.com/jekyllrb
  - title: linkedin
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: linkedin
    url: http://bitbucket.org/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 


# Build settings
markdown: kramdown
permalink: pretty