url: 
baseurl:

# Site settings
title: DDSCC
email: info@ddscc.nl
description: "The Dutch Data Security and Compliance Community"


# Team names, titles and social links
people:
- name: Bram de Jager
  pic: 1
  position: Organisator
  social:
    - title: x
      url: #
    - title: linkedin
      url: #
    - title: github
      url: #

- name: Freerk Terpstra
  pic: 2
  position: Organisator
  social:
    - title: x
      url: #
    - title: linkedin
      url: #
    - title: github
      url: #

- name: René Laas
  pic: 3
  position: Organisator
  social:
    - title: x
      url: #
    - title: linkedin
      url: #
    - title: github
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: LinkedIn Pagina
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: LinkedIn Group
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 


# Build settings
markdown: kramdown
permalink: pretty