url: 
baseurl:

# Site settings
title: DDSCC
email: info@ddscc.nl
description: "Dutch Data Security & Compliance Community"


# Team names, titles and social links
people:
- name: Bram de Jager
  pic: 1
  pic_url: https://media.licdn.com/dms/image/C4E03AQEpHTurhuIkUw/profile-displayphoto-shrink_800_800/0/1526538536475?e=1727913600&v=beta&t=ChWvrc82vbMocfr6kRLW4tOFs6ewE5oH-GkKGIouokI
  position: Organisator
  social:
    - title: twitter
      url: https://x.com/bramdejager
    - title: linkedin
      url: https://www.linkedin.com/in/bramdejager/

- name: René Laas
  pic: 2
  pic_url: https://media.licdn.com/dms/image/C4D03AQHXhHCjoByNsg/profile-displayphoto-shrink_800_800/0/1625832708217?e=1727913600&v=beta&t=0KNTvud8YegiiMWvPiKKjoboW-wHwU2cqdjeRS5IcT4
  position: Organisator
  social:
    - title: twitter
      url: https://x.com/mr_helaas
    - title: linkedin
      url: https://www.linkedin.com/in/renelaas/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: meetup
    url: https://www.meetup.com/nl-NL/dutch-data-security-compliance-community/
  - title: linkedin
    url: https://www.linkedin.com/company/ddscc/

# Postal address (add as many lines as necessary)
address:
  - line: 


# Build settings
markdown: kramdown
permalink: pretty